### ISSUE TITLE
Feature: hide latest news notification badge

### ISSUE THREAD

**Issue by ntorrey** [surrealdb/surrealist#526] opened 2024-10-18 13:57 UTC
### Is your feature request related to a problem?

This is kind of a minor nitpick, but the 'eternal' little-pink-notification-badge on the 'latest news' button is bothersome to my OCD. I think it would be preferable to hide the notification when the latest news button is clicked and only show it again if there are new articles.
![2024-10-18 09 55 28](https://github.com/user-attachments/assets/ea4015ce-ee79-44a5-b202-9e5748fe65f2)

### Describe the solution

See above

### Surrealist Environment

Version: 3.0.6
Flags: feature_flags: true, query_view: true, explorer_view: true, graphql_view: true, designer_view: true, auth_view: true, functions_view: true, models_view: true, apidocs_view: true, cloud_view: true, themes: true, newsfeed: true, database_version_check: false, highlight_tool: false, legacy_serve: false, cloud_endpoints: production, cloud_access: false, cloud_killswitch: true, changelog: auto

### Contact Details

via this github issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by macjuul** [comment] 2024-10-25 13:27
I have been unable to reproduce this behaviour after testing, nor should it be possible to happen. It may have been caused by a one off fluke.

I'll close this issue for now, however if this problem continues to persist feel free to reopen it.

**Closed by macjuul** 2024-10-25 13:27 UTC
Labels: feature
