### ISSUE TITLE
[v2] Error on adding arguments to function

### ISSUE THREAD

**Issue by oskar-gmerek** [surrealdb/surrealist#196] opened 2024-04-23 16:19 UTC
**Describe the bug**
When we try to add argument during creating new function, we will get an error instead of form.

https://github.com/surrealdb/surrealist/assets/53402105/15a03e82-69a0-4e2d-a8b8-e20b0d469aa2

**To Reproduce**
1. Go to `Functions` in Surrealist menu
2. Create new function for ex. `fn::test`
3. Click on `+` to add new Argument
4. See the error
5. From this point you need to create a new connection (is impossible to use existing connection as there is no way to choose it)

**Expected behavior**
1. App should not end with the error and display form for adding argument
2. After error there should be possible to use Surrealist as before the error occur, or at least there should be a menu with saved connections on the landing screen

**Environment:**
```
Paste your environment here by following these steps
Platform: Desktop
OS: Darwin
Architecture: x86_64
WebView: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko)
Version: 2.0.0
Flags: featureFlags: false, models_view: true, apidocs_view: true, themes: false, newsfeed: true
```

and similar on:
```
Platform: Desktop
OS: Darwin
Architecture: aarch64
WebView: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko)
Version: 2.0.0
Flags: featureFlags: false, models_view: true, apidocs_view: true, themes: false, newsfeed: true
```
but, on Macbook (2nd one) there is at least a menu to fill out new connection form with template (but this still creating new unnecessary connection).

**Comment by branislav91srb** [comment] 2024-04-23 16:21
I have the same problem.

**Comment by macjuul** [comment] 2024-04-23 16:22
Duplicate of #194 

Already fixed and will be included in the next patch release!

**Closed by macjuul** 2024-04-23 16:22 UTC
Labels: bug
