### ISSUE TITLE
launch after install

### ISSUE THREAD

**Issue by GiveMeFox** [surrealdb/surrealist#252] opened 2024-05-01 14:00 UTC
**Describe the bug**
A clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem.
![image](https://github.com/surrealdb/surrealist/assets/74460065/688c7f35-ffbc-4cab-8f1f-21bd690f5168)

**To Reproduce**
1. download Surrealist_2.0.4_x64_en-US.msi
2. run it
3. click launch after the wizard finishes the install

**Expected behavior**
a normal interface

**Environment:**
windows 11

Paste your environment here by following these steps
Edition	        Windows 11 Pro
Version	        21H2
Installed on	‎10.‎10.‎2023
OS build	        22000.2538
Experience	Windows Feature Experience Pack 1000.22001.1000.0

**Comment by macjuul** [comment] 2024-05-01 14:45
My apologies for the app not working. Could you open the developer console to see if it contains any warnings or errors?
https://surrealdb.com/docs/surrealist/getting-started/settings-and-customisation#opening-the-developer-console

**Comment by macjuul** [comment] 2024-05-01 16:04
What does it look like when switching to the network tab? It looks like no resources are being loaded, which I personally cannot reproduce

Does the web app work as intended?

**Comment by reinhard-sanz** [comment] 2024-05-02 09:25
Hello got the same issue after upgrading to 2.0.4.
Just blank screen for me.
Apart from this error, console is empty:
<img width="199" alt="image" src="https://github.com/surrealdb/surrealist/assets/124268086/5d468c84-dcb1-43d6-b43e-b26e656f8438">

Network looks like this for me:
<img width="746" alt="image" src="https://github.com/surrealdb/surrealist/assets/124268086/8f7435df-10c9-4c8f-acda-e306a0a695d3">

Seems to be a caching issue, clearing the browser cache for the failed routes fixed it for me:
<img width="191" alt="image" src="https://github.com/surrealdb/surrealist/assets/124268086/142d640e-98e5-4d43-8e2a-4e54a7c6c09e">

**Comment by macjuul** [comment] 2024-09-05 08:32
This was likely a temporary caching issue hence I will close it for now

**Closed by macjuul** 2024-09-05 08:32 UTC
Labels: bug, cannot reproduce
