### ISSUE TITLE
Stuck at "Connecting..."

### ISSUE THREAD

**Issue by Icaruk** [surrealdb/surrealist#139] opened 2023-10-29 21:52 UTC
**Describe the bug**

I can connect successfully with:
` surreal sql --conn https://surrealdb.icaruk.dev --user icaruk --pass mypass --ns test --db test --pretty`

But I can't connect using:

![image](https://github.com/StarlaneStudios/Surrealist/assets/10779469/25aa2f51-ac10-41f1-85e4-0b228f3d877b)

How I started the server:

`surreal start --log info --user icaruk --pass mypass --bind 0.0.0.0:1234 --file:mydb.db`

**Environment (you can view the current version under Settings):**
 - Operating System: Windows 11
 - Surrealist Version: 1.11.0
 - SurrealDB Version: surreal 1.0.0-beta.8+20220930.c246533 for windows on x86_64
 
 
 EDIT:
 
I uninstalled surrealdb and reinstalled again.
Now it works. But when I change some param to something wrong there is no error message.

**Comment by jimreesman** [comment] 2023-11-11 20:31
I have the same problem. A connection string + { db, ns, username, password } that works from command line fails to connect in Surrealist. And unfortunately, Surrealist gives no information about the problem.

**Comment by dtwiers** [comment] 2023-11-14 23:11
yep, same here. I can connect in command line and postman, but not in surrealist.app or the desktop app.

**Comment by stephaneBalelos** [comment] 2023-11-27 10:43
Any update on this? My surrealDB instance is running in a Docker Container

**Comment by jimreesman** [comment] 2023-11-27 12:34
In case it helps anyone else, our problem seemed to stem from AWS Elasticbeanstalk default settings. We are running our very simple containers in EB. The listeners (80,443) were configured by default to allow HTTP/HTTPS only. Modifying that to allow all TCP allowed connection from Surrealist.

**Comment by macjuul** [comment] 2024-04-26 21:53
Since a lot has changed in the past months I'll go ahead and close this issue as I have not been able to reproduce it, and may be fixed in Surrealist 2.0. If this problem persists feel free to create a new issue

**Closed by macjuul** 2024-04-26 21:53 UTC
Labels: bug
