### ISSUE TITLE
Field Permissions incorrect

### ISSUE THREAD

**Issue by andreinistor** [surrealdb/surrealist#383] opened 2024-08-12 15:34 UTC
**Describe the bug**
When setting PERMISSIONS on a table to FULL (clicking on ✅ for each Create, Select, Update, Delete), it incorrectly sets each defined field to:

`DEFINE FIELD can_be_sold ON product TYPE bool PERMISSIONS FOR select, create, update, delete WHERE FULL`

**To Reproduce**
DEFINE a table.
DEFINE some fields.
Go to Table Permissions.
Then clicking on ✅ for each Create, Select, Update, Delete

**Expected behavior**
When setting FULL permissions, don't add **WHERE**.

**Comment by ragavpr** [comment] 2024-08-24 10:40
I just ran into this,

For now, the workaround is to, just to toggle permissions in the GUI to `NONE`, then `FULL` in each CREATE, SELECT, UPDATE, DELETE for every newly created field or any field you intend to fix immediately.

The problem is with initial default values for the permission, will address it in a PR shortly.

Even after the fix, the old incorrect permissions in your database "... `WHERE FULL`" must be manually changed to "... `FULL`"

**Comment by macjuul** [comment] 2024-08-30 12:06
This has been fixed in #394

**Closed by macjuul** 2024-08-30 12:06 UTC
Labels: bug
