### ISSUE TITLE
surrealist error: n is  undefined

### ISSUE THREAD

**Issue by yghaderi** [surrealdb/surrealist#411] opened 2024-09-06 07:41 UTC
surrealdb v2 beta2
**Describe the bug**
I define this table.
DEFINE TABLE instrument SCHEMAFULL;
DEFINE FIELD ins_code ON TABLE instrument TYPE string;
DEFINE FIELD name ON TABLE instrument TYPE string;
DEFINE FIELD symbol ON TABLE instrument TYPE string;
DEFINE FIELD category ON TABLE instrument TYPE  
    {type:"Stock", class:"Equity"} | 
    {type:"ETF", class:"Equity", leveraged:bool}|
    {type:"ETF", class:"FixedIncome"}|
    {type:"ETF", class:"Commodity", leveraged:bool}|
    {type:"Bond", class:"FixedIncome"} |
    {type:"Option", class:"Derivative"};
DEFINE FIELD activity ON TABLE instrument TYPE record<activity>;
DEFINE FIELD market ON TABLE instrument TYPE record<market>;

and after run query, it will be define.

**To Reproduce**
1. Go to 'surrealist'
2. Click on 'designer'
3.See error

![Screenshot from 2024-09-06 10-54-32](https://github.com/user-attachments/assets/7c7a2ddd-f4d6-4c70-8137-8f969576739e)

**Comment by macjuul** [comment] 2024-09-06 09:07
Thanks for reporting your issue! This happens because the latest stable release of Surrealist isn't compatible with the SurrealDB 2.0 beta releases. You can instead use the [Surrealist 3.0 beta](https://surrealdb.com/blog/surrealist-3-0-beta) which is compatible and should not throw this error. Hope that helps!

**Comment by TheRangiCrew** [comment] 2024-09-06 14:13
In 3.0 this issue seems to occur only when a literal type is defined in a field. I am experiencing the issue using Surrealist 3.0-beta.1 in the browser. Cannot test in desktop since issue #399 occurs.

### Tested Queries
`DEFINE FIELD IF NOT EXISTS wmo ON TABLE text_product TYPE s"literal string"`
`DEFINE FIELD IF NOT EXISTS wmo ON TABLE text_product TYPE {
    datatype: string,
    issued: datetime,
    original: string,
    wfo: string
};`

### Version information:
Platform: Web
Navigator: Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0
Version: 3.0.0-beta.1
Flags: feature_flags: false, query_view: true, explorer_view: true, graphql_view: true, designer_view: true, auth_view: true, functions_view: true, models_view: true, apidocs_view: true, cloud_view: true, themes: true, newsfeed: true, database_version_check: false, highlight_tool: false, legacy_serve: false, cloud_endpoints: production, cloud_access: false, changelog: hidden


![image](https://github.com/user-attachments/assets/9ab4959b-ae46-422a-a134-10e3c9a86a1c)

**Comment by TheRangiCrew** [comment] 2024-09-06 15:45
This seems to be fixed after cloning the most recent commits to main. Working in dev environment.

**Comment by macjuul** [comment] 2024-09-06 15:49
I cannot reproduce it on my side either using the provided queries, so it looks like it's fixed! I'll close this again for now but if you do believe the issue continues to persist I'll reopen it again. Thanks!

**Closed by macjuul** 2024-09-06 15:49 UTC
Labels: bug
