### ISSUE TITLE
Bug: Database export produce syntax error

### ISSUE THREAD

**Issue by lkwr** [surrealdb/surrealist#382] opened 2024-08-12 10:08 UTC
**Describe the bug**

The export method in Surrealist produces a invalid `.surql`-file when a table starts with `table` or is exactly `table`.

**To Reproduce**

1. Execute this query on a blank instance:

```surql
DEFINE TABLE table;
DEFINE FIELD name ON TABLE table TYPE string;
```

2. Export the database with the Surrealist export method.

3. Try to import the file into a new blank instance. A successful popup will appear but nothing happend in the background.

**Expected behavior**

Exporting and then importing work as expected.

**Problem**

The exported `.surql`-file contains a syntax error here:

```
-- ------------------------------
-- Export generated by Surrealist on 2024-08-12T09:37:51.128Z
-- ------------------------------

OPTION IMPORT;

-- ------------------------------
-- TABLE: table
-- ------------------------------

DEFINE TABLE table TYPE ANY SCHEMALESS PERMISSIONS NONE;

DEFINE FIELD name ON table TYPE string PERMISSIONS FULL;
--                         ^ - Here SurrealQL thinks "TYPE" is the table because
--                             `ON table` is interpreted as the keyword but only `ON`
--                             is the keyword and `table` is the actual table name.
```

**Solution**

Add an additional `TABLE` after `ON` (`ON TABLE`) in the export generator.

```diff
-DEFINE FIELD name ON table TYPE string PERMISSIONS FULL;
+DEFINE FIELD name ON TABLE table TYPE string PERMISSIONS FULL;
```

The syntax error occurs not only in the `DEFINE FIELD` statements but also in cases like `DEFINE INDEX` when using a table named `table`.

I don't know if it is a SurrealDB or Surrealist problem but this does not work with the latest stable (1.5.4 linux/aarch64) and the latest nightly (2.0.0+20240808.3f5ef43 linux/aarch64).

**Environment:**
```
Version: 2.1.6
Flags: feature_flags: false, models_view: true, apidocs_view: true, themes: false, newsfeed: true, database_version_check: true, highlight_tool: false, surreal_compat: v1, changelog: auto
```

**Comment by macjuul** [comment] 2024-08-12 14:28
Thanks for finding this issue! It actually appears to be caused by an issue within SurrealDB itself, namely the `INFO FOR` statement.

We will find a suitable solution for this as soon as possible

Thanks again!

**Comment by macjuul** [comment] 2024-08-30 14:53
This has now been fixed in SurrealDB. Thanks for the issue!

**Closed by macjuul** 2024-08-30 14:53 UTC
Labels: bug
