### ISSUE TITLE
Editor crashes when moving blocks

### ISSUE THREAD

**Issue by dignakov** [surrealdb/surrealist#221] opened 2024-04-25 12:02 UTC
**Describe the bug**
When moving tables around, the editor crashes

**To Reproduce**
add a couple of blocks, and move them around

**Expected behavior**

**Environment:**

```
Platform: Web
Navigator: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Version: 2.0.2
Flags: featureFlags: false, models_view: true, apidocs_view: true, themes: false, newsfeed: true
```
<img width="789" alt="image" src="https://github.com/surrealdb/surrealist/assets/810523/ab37f6b9-e7b8-41ed-8807-8f6ef44c2f08">

**Comment by macjuul** [comment] 2024-04-25 12:04
Duplicate of https://github.com/surrealdb/surrealist/issues/216

**Closed by macjuul** 2024-04-25 12:04 UTC
Labels: bug
