### ISSUE TITLE
Show record links option throws an error (shape does not exist!)

### ISSUE THREAD

**Issue by ryu-man** [surrealdb/surrealist#355] opened 2024-07-05 22:18 UTC
**Describe the bug**
I have a +100 table database; in the beginning, the show record links function was working normally, but at some point it stopped working; nothing would render when it was activated, and the console printed the following message:

![image](https://github.com/surrealdb/surrealist/assets/25468773/40f7ddf4-3b16-4212-b83d-220e5f8fdb50)

**Environment:**
```
Paste your environment here by following these steps
Platform: Desktop
OS: windows
Architecture: x86_64
WebView: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0
Version: 2.1.2
Flags: feature_flags: false, models_view: true, apidocs_view: true, themes: false, newsfeed: true, database_version_check: true, highlight_tool: false, surreal_compat: v1, changelog: auto
```

**Comment by macjuul** [comment] 2024-08-30 12:18
This has been fixed in #394

It was caused by incorrectly configured relation tables. As of the next release Surrealist will render the table graph even if it finds issues, and instead will list these out under a new warning section 🙂

**Closed by macjuul** 2024-08-30 12:18 UTC
Labels: bug
