### ISSUE TITLE
Sidebar is broken on firefox

### ISSUE THREAD

**Issue by TudorAndrei** [surrealdb/surrealist#210] opened 2024-04-24 08:31 UTC
**Describe the bug**
![image](https://github.com/surrealdb/surrealist/assets/25133006/b8e232c3-a4c1-40a8-ba46-6580804b6774)

The sidebar is broken on the webclient

**To Reproduce**
1. open surrealist.app on the browser

**Expected behavior**
just the icons to appear,

**Environment:**
```
Platform: Web
Navigator: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0
Version: 2.0.1
Flags: featureFlags: false, models_view: true, apidocs_view: true, themes: false, newsfeed: true
```

**Comment by macjuul** [comment] 2024-04-24 09:54
I personally cannot reproduce this issue on Firefox version 125 for both Mac and Arch. Is this only happening on Firefox?

**Comment by TudorAndrei** [comment] 2024-04-24 10:28
On chrome, I don't have the issue

**Comment by giodamelio** [comment] 2024-06-21 20:21
I am getting this same issue using the Desktop App.

I am using a weird NixOS build of the app ([from this PR](https://github.com/NixOS/nixpkgs/pull/307031)) and also using a tiling window manager (Sway) on Wayland. So I don't really expect everything to work out of the box.

I might be able to help debug though.

**Comment by macjuul** [comment] 2024-09-05 08:30
After consideration I have decided to close this issue for now as I can still not reproduce it. This may have been caused by some obscure browser compatibility or configuration, however there is nothing I can do from my side to fix this currently.

**Closed by macjuul** 2024-09-05 08:30 UTC
Labels: bug, cannot reproduce
