### ISSUE TITLE
Defining record type without table breaks explorer and designer

### ISSUE THREAD

**Issue by singersbalm** [surrealdb/surrealist#169] opened 2024-01-27 09:07 UTC
**Describe the bug**
I tried to define the record type for a table. Every other type seems to work, but it will always show No tables found once the type is defined. I used the rust lib to create the db and execute the queries. `INFO FOR DB` still works and shows the table.

**To Reproduce**
```
DEFINE TABLE kinds SCHEMAFULL;
DEFINE FIELD other_key ON TABLE kinds TYPE record;
```
or 

file kind = SpeeDb, namespace and db both test
[db.zip](https://github.com/StarlaneStudios/Surrealist/files/14071711/db.zip)
`surreal start --log debug --user root --pass root speedb:/Path/To/Db`

**Expected behavior**
Should show tables

**Environment (you can view the current version under Settings):**
 - Operating System: macOS 
 - Surrealist Version: 1.11.3
 - SurrealDB Version:1.1.1+20240122.af412132.dirty for macos on aarch64 //compiled 3 days ago from source

**Comment by macjuul** [comment] 2024-01-27 13:12
This is caused by a known issue in SurrealDB where `TYPE record` isn't parsing correctly, causing issues for Surrealist. It should be fixed in the next release of SurrealDB. Until then I'll leave this issue open in case more people run into it.

Related #161

**Comment by michelemoretti** [comment] 2024-02-12 09:49
I seem to be able to reproduce even with the surreal nightly docker (which should have merged a fix https://github.com/surrealdb/surrealdb/pull/3306)) and the latest version of Surrealist 1.11.3

**Comment by macjuul** [comment] 2024-02-12 17:17
@michelemoretti Surrealist embeds the SurrealDB rust crate for certain operations, which is likely why it is still not working as expected. I'm currently working on a Surrealist update which will fix this issue.

**Comment by macjuul** [comment] 2024-04-25 11:15
This should now be working as expected in Surrealist 2.0

**Closed by macjuul** 2024-04-25 11:15 UTC
Labels: bug
