### ISSUE TITLE
Bug: Blank Screen after launch 3.0.0

### ISSUE THREAD

**Issue by gander** [surrealdb/surrealist#445] opened 2024-09-17 17:39 UTC
### Describe the bug

Blank screen.

![obraz](https://github.com/user-attachments/assets/61371b87-d154-4d61-9bfd-d6a59ddf6a7f)

### Steps to reproduce

Install 3.0.0 from amd64 deb package. Run `surrealist`.

### Expected behaviour

Working app.

### Surrealist Environment

N/A

[surrealist.log](https://github.com/user-attachments/files/17032811/surrealist.log)

### Contact Details

flyer-slit-onshore@duck.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gander** [comment] 2024-09-17 17:48
I used [perplexity](https://go.gander.pl/perplexity.ai-pro) to try to solve the problem myself and the first hint helped:

```shell
WEBKIT_DISABLE_DMABUF_RENDERER=1 surrealist
```

[surrealist-fixed.log](https://github.com/user-attachments/files/17032911/surrealist-fixed.log)

**Comment by gander** [comment] 2024-09-17 18:12
The application hangs, both when I try to create a new connection or start a local sandbox. No lines in the log.

**Comment by lcdss** [comment] 2024-09-17 19:27
At least here, using the appimage build, I can't do anything without freezing the whole app and getting a blank screen.

**Comment by macjuul** [comment] 2024-09-17 20:10
This is a duplicate of #276 or #424

**Closed by macjuul** 2024-09-17 20:10 UTC
Labels: bug, triage

**Comment by zvictor** [comment] 2024-09-19 12:48
@macjuul I am not sure this is the same issue.

I'd never had blank screen problems until v3.0.2.
If I rollback to v3.0.1 it works fine. The problem in my machine only happens in v3.0.2.

---

> WEBKIT_DISABLE_DMABUF_RENDERER=1 surrealist

This command didn't help here.
@gander what versions have you tried? Is there a difference between v3.0.1 and v3.0.2 for you?

**Comment by zvictor** [comment] 2024-09-19 12:51
Okay, I just noticed https://github.com/surrealdb/surrealist/issues/424#issuecomment-2359458272.
We better keep the conversation there.

**Comment by lcdss** [comment] 2024-09-19 18:44
I installed it using the deb build and now it works, but with the appimage build it doesn't, in any v3 version so far.
