### ISSUE TITLE
Surrealist encountered an error

### ISSUE THREAD

**Issue by LucyEgan** [surrealdb/surrealist#350] opened 2024-07-01 06:58 UTC
**Describe the bug**
"Surrealist encountered an error" screen appears when returning bytes data 
<img width="502" alt="image" src="https://github.com/surrealdb/surrealist/assets/5268652/cb34c00e-cd09-424a-b8b1-895fe78f3022">

**To Reproduce**
Run `<bytes>"cake"` in query view

**Expected behavior**
See the binary data of the response in some nerd readable format

**Environment:**
```
Platform: Desktop
OS: windows
Architecture: x86_64
WebView: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0
Version: 2.1.2
Flags: feature_flags: true, models_view: true, apidocs_view: true, themes: true, newsfeed: true, database_version_check: false, highlight_tool: true, surreal_compat: v2, changelog: auto
```

**Comment by macjuul** [comment] 2024-07-01 09:09
Duplicate of #249

**Closed by macjuul** 2024-07-01 09:09 UTC
Labels: bug
