### ISSUE TITLE
Format Query Removes Comments

### ISSUE THREAD

**Issue by PSmouz** [surrealdb/surrealist#335] opened 2024-06-11 18:08 UTC
When formatting a query in the editor all comments are being removed. I don't know if this is done on purpose but I find it oddly annoying.

**Comment by macjuul** [comment] 2024-06-12 07:30
Closing as duplicate of https://github.com/surrealdb/surrealist/issues/265

[This is a limitation of the current formatter](https://github.com/surrealdb/surrealist/issues/265#issuecomment-2130283578)

**Closed by macjuul** 2024-06-12 07:30 UTC
Labels: bug
